// Animation timing constants (ms)
export const ANIMATION = {
  REDACT_DURATION: 1200,
  SPY_REVEAL_DELAY: 1000,
  LOCATION_REVEAL_DELAY: 1600,
  ROLES_REVEAL_BASE_DELAY: 2000,
  ROLES_REVEAL_STAGGER: 200,
  CLASSIFIED_TRANSITION_DELAY: 800,
  ACHIEVEMENT_TOAST_BASE_DELAY: 2500,
  ACHIEVEMENT_TOAST_STAGGER: 1500,
  ACHIEVEMENT_TOAST_DURATION: 4000,
  REVEAL_SOUND_DELAY: 200,
};

// Game limits
export const LIMITS = {
  MAX_PLAYERS: 12,
  MIN_PLAYERS: 3,
  MIN_PLAYERS_DOUBLE_AGENT: 5,
  MAX_CUSTOM_LOCATIONS: 20,
  MAX_NAME_LENGTH: 20,
  MAX_LOCATION_NAME_LENGTH: 40,
  ROLES_PER_LOCATION: 8,
};
